---
- hosts: all
  roles:
          - { name: common, tags: common }
          - { role: virtual,  when: ansible_virtualization_role == "guest" }
          - { role: physical, when: not ansible_virtualization_role == "guest" }
          - { name: dotfiles, tags: dotfiles }

- include: dns.yml
- include: web.yml
- include: mail.yml
