---
- hosts: all
  roles:
          - common
          - { role: virtual,  when: ansible_virtualization_role == "guest" }
          - { role: physical, when: not ansible_virtualization_role == "guest" }
          - dotfiles

#- include: dns.yml
- include: web.yml
#- include: mail.yml
