---

- name: Install mail related packages
  package: name="{{item}}" state=present
  with_items:
          - dovecot-core
          - dovecot-imapd
          - dovecot-sieve
          - dovecot-managesieved
          - opendkim
          - opendkim-tools
          - postfix
          - postfix-policyd-spf-python
          - postgrey

- name: Configure postfix from template
  template: src=postfix/main.cf dest=/etc/postfix/main.cf owner=root group=root mode=0644

- name: Configure remaining postfix files
  copy: src=postfix/master.cf dest=/etc/postfix/master.cf owner=root group=root mode=0644

- name: Configure mail aliases
  copy: src=aliases dest=/etc/aliases owner=root group=root mode=0644

- name: Update aliases database
  command: /usr/sbin/postalias /etc/aliases

- name: Configure Opendkim
  template: src=opendkim/opendkim.conf dest=/etc/opendkim.conf owner=root group=root mode=0644

- name: Configure Postgrey
  copy: src=postgrey/default dest=/etc/default/postgrey owner=root group=root mode=0644

- name: Configure Dovecot
  copy: src=dovecot/local.conf dest=/etc/dovecot/local.conf owner=root group=root mode=0644
