---

- name: Add my authorized keys
  authorized_key: user=root key="https://github.com/PedroArvela.keys"

- name: Generate sshd_config
  template: src=ssh/sshd_config dest=/etc/ssh/sshd_config mode=600
  notify: restart sshd

- name: Generate common locales
  locale_gen: name="{{item}}" state=present
  with_items:
          - en_US.UTF-8
          - pt_PT.UTF-8

- name: Set the default locale for Debian systems
  copy: src=locale dest=/etc/default/locale owner=root group=root mode=0644

- name: Set timezone file for Debian systems
  copy: src=timezone dest=/etc/timezone owner=root group=root mode=0644

- name: Set localtime symlink
  file: src=/usr/share/zoneinfo/Europe/Lisbon dest=/etc/localtime state=link force=yes

- name: Install Unattended Upgrades
  package: name="{{item}}" state=present
  with_items:
          - unattended-upgrades
          - apt-listchanges

- name: Set up Unattended Upgrades
  copy: src=apt/20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

- name: install utilities
  package: name="{{item}}" state=present
  with_items:
          - bash-completion
          - dnsutils
          - git
          - htop
          - lsof
          - tmux
          - tree
          - vim
